import { useSeoMeta } from "@unhead/react";

const About = () => {
  useSeoMeta({
    title: "About - Character News",
    description: "Learn more about Character News",
  });

  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-gray-100 dark:bg-gray-900">
      <div className="max-w-prose text-center space-y-4">
        <h1 className="text-2xl font-bold">About Character News</h1>
        <p className="text-gray-700 dark:text-gray-300">
          Character News delivers headlines contextualized by various fictional
          characters. Summaries are generated by AI and posted to Nostr.
        </p>
      </div>
    </div>
  );
};

export default About;
